In [1]:
import torch

In [2]:
import torchvision

In [3]:
torch.cuda.is_available()

True

### Torch Tensors

In [21]:
#1-D tensor
a = torch.tensor([1,2,3,4,5])
print(a)
print(a.shape)
print(a.size())

tensor([1, 2, 3, 4, 5])
torch.Size([5])
torch.Size([5])


In [28]:
print(a.view(-1,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [22]:
#2-D tensor
b = torch.tensor([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([2, 3])


In [33]:
print(b.view(-1,1))
print(b.view(3,2))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [43]:
#3-D tensor with 2 channels, 2 rows, 3 columns
c = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(c.size())
print(c.view(-1,1))
print(c.view(2, -1))

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [41]:
#4-D tensor
d = torch.rand(4,4)
print(d)
print(d.shape)
print(d.size())

tensor([[0.1304, 0.9367, 0.2787, 0.3087],
        [0.6205, 0.2898, 0.6436, 0.3211],
        [0.3861, 0.4135, 0.9724, 0.9078],
        [0.5933, 0.1518, 0.5974, 0.7014]])
torch.Size([4, 4])
torch.Size([4, 4])


In [20]:
#size of tensors
print(a.size()) 
print(a.shape)

torch.Size([5])
torch.Size([5])


In [27]:
#float tensor
e = torch.FloatTensor([[1,2,3],[4,5,6]])
print(e)
print(e.mean())
print(e.std())
print(e.median())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(3.5000)
tensor(1.8708)
tensor(3.)


In [26]:
#double tensor
f = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(f)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [45]:
f = torch.randint(0,10,(3,3))
print(f)
print(f.type())

tensor([[3, 9, 4],
        [2, 8, 9],
        [3, 6, 2]])
torch.LongTensor


In [52]:
g = torch.ones(3,3, dtype= torch.int32)
print(g)
print(g.type())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.IntTensor


In [53]:
h = torch.rand_like(g, dtype= torch.float)
print(h)

tensor([[0.6891, 0.7292, 0.6401],
        [0.9314, 0.8290, 0.3048],
        [0.3895, 0.2311, 0.7545]])


In [54]:
#add two tensors
i  = torch.add(g,h)
print(i)

tensor([[1.6891, 1.7292, 1.6401],
        [1.9314, 1.8290, 1.3048],
        [1.3895, 1.2311, 1.7545]])


In [55]:
torch.add(g,h, out=i)
print(i)

tensor([[1.6891, 1.7292, 1.6401],
        [1.9314, 1.8290, 1.3048],
        [1.3895, 1.2311, 1.7545]])


In [56]:
h.add_(g)
print(h)

tensor([[1.6891, 1.7292, 1.6401],
        [1.9314, 1.8290, 1.3048],
        [1.3895, 1.2311, 1.7545]])


In [57]:
print(h[0,0])

tensor(1.6891)


In [60]:
print(h[1,:])

tensor([1.9314, 1.8290, 1.3048])


In [62]:
element = h[1,1]    #accessing element
print(element)

element = h[1,1].item()    #extracting the element
print(element)


tensor(1.8290)
1.8290350437164307
