### Autograd

In [2]:
import torch


In [5]:
# Create tensors.
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = torch.ones(2, 2, requires_grad=True)
print(y)
z = x + y
print(z)
print(z.grad_fn)
s = z.sum()
print(s)
print(s.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor(8., grad_fn=<SumBackward0>)


In [6]:
# backpropagation on s.
s.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
# freeze the gradient.
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = torch.ones(2, 2, requires_grad=True)
print(y)
with torch.no_grad():
    z = x + y
print(z)
print(z.grad_fn)
s = z.sum()
print(s)
print(s.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
None
tensor(8.)
None


In [13]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 1
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[12., 12.],
        [12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)
tensor([[3., 3.],
        [3., 3.]])
