In [1]:
import torch
import torch.nn as nn

In [41]:
prediction = torch.randn(4,5)
prediction

tensor([[-1.5136,  0.8902, -1.0560,  0.6902,  0.2704],
        [-0.1090,  0.6959,  1.6532,  0.2639, -0.2012],
        [-0.4967, -0.6778, -0.6281,  1.5430, -1.1198],
        [ 1.1275,  0.0789, -0.0590,  0.8203, -0.7955]])

In [42]:
label = torch.randn(4,5)
label

tensor([[ 0.6004, -1.1126,  1.4351, -0.5764, -0.2718],
        [ 0.4514,  0.2549,  0.1090, -2.3775, -0.9566],
        [ 0.1068, -0.1529, -1.8295, -0.7046,  0.7793],
        [ 1.3304,  0.1509, -0.9412, -1.2087,  0.2738]])

In [43]:
mse = nn.MSELoss(reduction='mean')

In [44]:
loss = mse(prediction, label)
loss

tensor(2.1925)

In [45]:
((prediction - label)**2 ).mean()

tensor(2.1925)

In [46]:
prediction

tensor([[-1.5136,  0.8902, -1.0560,  0.6902,  0.2704],
        [-0.1090,  0.6959,  1.6532,  0.2639, -0.2012],
        [-0.4967, -0.6778, -0.6281,  1.5430, -1.1198],
        [ 1.1275,  0.0789, -0.0590,  0.8203, -0.7955]])

In [47]:
label = torch.zeros(4,5).random_(0,2)
label

tensor([[1., 1., 1., 1., 0.],
        [1., 0., 1., 0., 1.],
        [1., 1., 0., 1., 0.],
        [1., 1., 0., 1., 1.]])

In [48]:
sigmoid = nn.Sigmoid()

In [49]:
bce = nn.BCELoss(reduction='mean')

In [50]:
bce(sigmoid(prediction), label)

tensor(0.7204)

In [51]:
bces = bce = nn.BCEWithLogitsLoss(reduction='mean')

In [52]:
bces(prediction, label)

tensor(0.7204)

In [53]:
import numpy as np
x = prediction.numpy()
y = label.numpy()

In [54]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [55]:
sigmoid(x)

array([[0.1804    , 0.7089386 , 0.25807413, 0.66601723, 0.5671888 ],
       [0.47277635, 0.6672683 , 0.839317  , 0.56558496, 0.44987014],
       [0.37830958, 0.33676222, 0.34794295, 0.8239024 , 0.24604881],
       [0.7553805 , 0.51970315, 0.48525056, 0.69429547, 0.3109924 ]],
      dtype=float32)

In [57]:
x = sigmoid(x)
loss_values = []
for i in range(len(y)):
    batch_loss = []
    for j in range(len(label[0])):
            batch_loss.append(np.log(1 + np.exp(-y[i][j] * prediction[i][j])))
    loss_values.append(np.mean(batch_loss))

print(np.mean(loss_values))


0.7210746
