In [1]:
import torch
import numpy as np

In [2]:
# Create a tensor
x = torch.tensor([1, 2, 3])
print(x)

# Move tensor to GPU
x = x.cuda()
print(x)

# Move tensor back to CPU
x = x.cpu()
print(x)

tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3])


In [4]:
# concatenate two tensors
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.cat([x, y], dim=0)
print(x)
print(y)
print(z)
a = torch.cat([x, y], dim=1)
print(a)

tensor([[ 1.7291, -0.5611,  0.6458],
        [ 0.3605,  0.9974,  0.4158]])
tensor([[0.5476, 0.4731, 0.7816],
        [1.4784, 0.0441, 1.2103]])
tensor([[ 1.7291, -0.5611,  0.6458],
        [ 0.3605,  0.9974,  0.4158],
        [ 0.5476,  0.4731,  0.7816],
        [ 1.4784,  0.0441,  1.2103]])
tensor([[ 1.7291, -0.5611,  0.6458,  0.5476,  0.4731,  0.7816],
        [ 0.3605,  0.9974,  0.4158,  1.4784,  0.0441,  1.2103]])
