In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# The indices of the words represent the values in the lookup table
word_to_idx = {"I": 0, "love": 1, "PyTorch": 2, "and": 3, "TensorFlow": 4}
embeddings = nn.Embedding(5, 7) # 5 words in vocab, 7 dimensional embeddings
word_index = torch.tensor([word_to_idx["PyTorch"]], dtype=torch.long)
print(word_index)
print(embeddings(word_index))


tensor([2])
tensor([[-0.0665, -1.6362, -0.5086, -0.2291, -0.1309,  0.7459,  0.3214]],
       grad_fn=<EmbeddingBackward0>)


In [3]:
pytorch = embeddings(word_index)
print(pytorch)
print(pytorch.shape)

tensor([[-0.0665, -1.6362, -0.5086, -0.2291, -0.1309,  0.7459,  0.3214]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [6]:
all_indices = torch.tensor([w for w in range(5)], dtype=torch.long)
all_words = embeddings(all_indices)
print(all_indices)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[ 0.0721, -0.8922, -0.7451, -0.8127,  1.0311, -0.6423,  0.4994],
        [-0.0248, -0.6552,  1.3898,  0.5324,  0.0957, -1.5585,  0.2627],
        [-0.0665, -1.6362, -0.5086, -0.2291, -0.1309,  0.7459,  0.3214],
        [-0.1447, -0.7004, -0.0840,  1.0636, -0.0717, -0.7949,  0.4287],
        [ 1.0382,  2.5951,  0.2455, -1.1577,  0.0424, -0.9611, -0.2042]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])
