### Softmax with Temperature

In [1]:
import torch
import torch.nn.functional as F

In [2]:
predictions = torch.log(torch.rand(3))

In [3]:
predictions

tensor([-1.0333, -0.5138, -0.3863])

In [5]:
print(F.softmax(predictions, dim=-1))

# Lower temperature, the higher the confidence of the model
print(F.softmax(predictions / 0.5, dim=-1))

tensor([0.2178, 0.3662, 0.4160])
tensor([0.1338, 0.3782, 0.4880])


In [6]:
print(F.softmax(predictions / 100, dim=-1))

tensor([0.3320, 0.3338, 0.3342])
