In [1]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset, DataLoader

In [2]:
# Load the data
df = pd.read_csv('diabetes.csv')
df.head()

Number of times pregnant  Plasma glucose concentration   
0                         6                           148  \
1                         1                            85   
2                         8                           183   
3                         1                            89   
4                         0                           137   

   Diastolic blood pressure  Triceps skin fold thickness   
0                        72                           35  \
1                        66                           29   
2                        64                            0   
3                        66                           23   
4                        40                           35   

   2-Hour serum insulin  Body mass index  Age     Class  
0                     0             33.6   50  positive  
1                     0             26.6   31  negative  
2                     0             23.3   32  positive  
3                    94             28.1   21  negative  
4                   168             43.1   33  positive

In [3]:
# For x extract all columns except the last one
x = df.iloc[:, 0:-1].values
# For y extract the last column
y_string = list(df.iloc[:, -1])

In [4]:
x

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

In [5]:
y_string

['positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',

In [6]:
# Convert the y_string to y integer
y_int = []
for i in y_string:
    if i == 'positive':
        y_int.append(0)
    else:
        y_int.append(1)

y_int

[0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,


In [7]:
# Convert the y_int to an array
y = np.array(y_int, dtype=np.float64)
y

array([0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 1.

In [8]:
# Feature Normalization
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[ 0.63994726,  0.84832379,  0.14964075, ..., -0.69289057,
         0.20401277,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.69289057,
        -0.68442195, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -0.69289057,
        -1.10325546, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ...,  0.27959377,
        -0.73518964, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.69289057,
        -0.24020459,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.69289057,
        -0.20212881, -0.87137393]])

In [9]:
# Convert the x and y to tensors
x = torch.tensor(x)
y = torch.tensor(y).unsqueeze(1)
x.shape, y.shape

(torch.Size([768, 7]), torch.Size([768, 1]))

In [10]:
class DiabetesDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.n_samples = x.shape[0]
        
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples
    

In [11]:
# Create the dataset using the class DiabetesDataset
dataset = DiabetesDataset(x, y)
len(dataset)

768

In [36]:
# Load the dataset using the dataloader
train_loader = DataLoader(dataset=dataset, batch_size=32, shuffle=True)

In [37]:
# visualize the train_loader data
print(f"Number of batches: {len(train_loader)}")
for x, y in train_loader:
    print(f"Data: {x.shape}, Labels: {y.shape}")
    break


Number of batches: 24
Data: torch.Size([32, 7]), Labels: torch.Size([32, 1])


![demo](https://user-images.githubusercontent.com/30661597/60379583-246e5e80-9a68-11e9-8b7f-a4294234c201.png)

In [39]:
# Create the model
class DiabetesModel(nn.Module):
    def __init__(self, input_features):
        super(DiabetesModel, self).__init__()
        self.fc1 = nn.Linear(input_features, 5)
        self.fc2 = nn.Linear(5, 4)
        self.fc3 = nn.Linear(4, 3)
        self.fc4 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
        self.tanh = nn.Tanh()

    def forward(self, x):
        out = self.fc1(x)
        out = self.tanh(out)
        out = self.fc2(out)
        out = self.tanh(out)
        out = self.fc3(out)
        out = self.tanh(out)
        out = self.fc4(out)
        out = self.sigmoid(out)
        return out

$H_{p}(q)=-\frac{1}{N} \sum_{i=1}^{N} y_{i} \cdot \log \left(p\left(y_{i}\right)\right)+\left(1-y_{i}\right) \cdot \log \left(1-p\left(y_{i}\right)\right)$


cost = -(Y * torch.log(hypothesis) + (1 - Y) * torch.log(1 - hypothesis)).mean()

In [40]:
# Create the model object
model = DiabetesModel(x.shape[1])
model

# Create the loss function
criterion = nn.BCELoss(reduction='mean')

# Create the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)




In [41]:
# Train the model
num_epochs = 200
for epoch in range(num_epochs):
    for x, y in train_loader:
        x = x.float()
        y = y.float()

        # Forward pass
        y_pred = model(x)
        loss = criterion(y_pred, y)
        
        # Backward pass
        loss.backward()
        
        # Update the parameters
        optimizer.step()
        
        # Zero the gradients
        optimizer.zero_grad()
        
    if (epoch+1) % 10 == 0:
        print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}")

    # Accuracy calculation
    output = (y_pred > 0.5).float()
    accuracy = (output == y).float().mean()
    print(f"Accuracy: {accuracy.item():.4f}")

Accuracy: 0.7500
Accuracy: 0.6875
Accuracy: 0.6875
Accuracy: 0.7188
Accuracy: 0.7188
Accuracy: 0.7188
Accuracy: 0.6562
Accuracy: 0.6562
Accuracy: 0.6250
Epoch: 10, Loss: 0.5677
Accuracy: 0.7188
Accuracy: 0.6562
Accuracy: 0.7500
Accuracy: 0.6875
Accuracy: 0.8125
Accuracy: 0.7812
Accuracy: 0.7188
Accuracy: 0.6250
Accuracy: 0.7500
Accuracy: 0.7500
Epoch: 20, Loss: 0.5757
Accuracy: 0.6562
Accuracy: 0.6875
Accuracy: 0.6562
Accuracy: 0.8438
Accuracy: 0.7500
Accuracy: 0.6875
Accuracy: 0.7500
Accuracy: 0.8125
Accuracy: 0.7188
Accuracy: 0.7812
Epoch: 30, Loss: 0.4775
Accuracy: 0.7188
Accuracy: 0.7812
Accuracy: 0.6875
Accuracy: 0.7812
Accuracy: 0.8750
Accuracy: 0.8438
Accuracy: 0.6562
Accuracy: 0.9062
Accuracy: 0.6562
Accuracy: 0.6562
Epoch: 40, Loss: 0.4157
Accuracy: 0.8125
Accuracy: 0.9062
Accuracy: 0.9062
Accuracy: 0.7812
Accuracy: 0.6875
Accuracy: 0.7500
Accuracy: 0.8125
Accuracy: 0.6875
Accuracy: 0.7812
Accuracy: 0.8438
Epoch: 50, Loss: 0.3355
Accuracy: 0.8750
Accuracy: 0.7188
Accuracy: 0.8